<?php
/**
 * The base configuration for WordPress
 *
 * This file has been auto-generated by Workpanel to support environment variables.
 */

// ** Database settings - You can get this info from your web host ** //
define( 'DB_NAME',     getenv('WORDPRESS_DB_NAME') ?: 'wp_database' );
define( 'DB_USER',     getenv('WORDPRESS_DB_USER') ?: 'wp_user' );
define( 'DB_PASSWORD', getenv('WORDPRESS_DB_PASSWORD') ?: 'password' );
define( 'DB_HOST',     getenv('WORDPRESS_DB_HOST') ?: 'localhost' );
define( 'DB_CHARSET',  'utf8' );
if ( ! defined( 'WP_CACHE' ) ) {
    // Kurulum sırasında (install.php) cache'i devre dışı bırakarak "table doesn't exist" hatasını engelle
    $is_installing = defined('WP_INSTALLING') || (isset($_SERVER['PHP_SELF']) && strpos($_SERVER['PHP_SELF'], 'install.php') !== false);
    define( 'WP_CACHE', !$is_installing );
}

/**#@+
 * Authentication unique keys and salts.
 * These are generated if not provided via environment variables.
 */
define( 'AUTH_KEY',         getenv('WORDPRESS_AUTH_KEY')         ?: 'put your unique phrase here' );
define( 'SECURE_AUTH_KEY',  getenv('WORDPRESS_SECURE_AUTH_KEY')  ?: 'put your unique phrase here' );
define( 'LOGGED_IN_KEY',    getenv('WORDPRESS_LOGGED_IN_KEY')    ?: 'put your unique phrase here' );
define( 'NONCE_KEY',        getenv('WORDPRESS_NONCE_KEY')        ?: 'put your unique phrase here' );
define( 'AUTH_SALT',        getenv('WORDPRESS_AUTH_SALT')        ?: 'put your unique phrase here' );
define( 'SECURE_AUTH_SALT', getenv('WORDPRESS_SECURE_AUTH_SALT') ?: 'put your unique phrase here' );
define( 'LOGGED_IN_SALT',   getenv('WORDPRESS_LOGGED_IN_SALT')   ?: 'put your unique phrase here' );
define( 'NONCE_SALT',       getenv('WORDPRESS_NONCE_SALT')       ?: 'put your unique phrase here' );

/**
 * WordPress database table prefix.
 */
$table_prefix = getenv('WORDPRESS_TABLE_PREFIX') ?: 'wp_';

/**
 * For developers: WordPress debugging mode.
 */
define( 'WP_DEBUG', (bool)getenv('WORDPRESS_DEBUG') ?: false );

/**
 * Reverse Proxy / SSL Support & Dynamic URLs
 */
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
    $_SERVER['HTTPS'] = 'on';
}

// Yönlendirme döngülerini engellemek için URL'leri dinamik belirle
$http_host = $_SERVER['HTTP_HOST'] ?? 'localhost';
$is_https = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https');
$protocol = $is_https ? 'https://' : 'http://';

define( 'WP_HOME', $protocol . $http_host );
define( 'WP_SITEURL', $protocol . $http_host );

/**
 * Custom Config Extra (Environment overrides)
 */
$configExtra = getenv('WORDPRESS_CONFIG_EXTRA');
if ($configExtra) {
    eval($configExtra);
}

/**
 * Redis Configuration
 */
if ( ! defined( 'WP_REDIS_HOST' ) ) {
    define( 'WP_REDIS_HOST', getenv('WP_REDIS_HOST') ?: (getenv('WORDPRESS_REDIS_HOST') ?: 'wordpress-redis') );
}
if ( ! defined( 'WP_REDIS_PORT' ) ) {
    define( 'WP_REDIS_PORT', getenv('WP_REDIS_PORT') ?: 6379 );
}


/**
 * Performance & Filesystem Settings
 */
if ( ! defined( 'FS_METHOD' ) ) {
    define( 'FS_METHOD', 'direct' );
}
if ( ! defined( 'WP_MEMORY_LIMIT' ) ) {
    define( 'WP_MEMORY_LIMIT', '512M' );
}
if ( ! defined( 'WP_MAX_MEMORY_LIMIT' ) ) {
    define( 'WP_MAX_MEMORY_LIMIT', '512M' );
}

// Post Revisions Limiti (Veritabanı Optimizasyonu)
define( 'WP_POST_REVISIONS', 3 );
define( 'EMPTY_TRASH_DAYS', 7 );
define( 'AUTOSAVE_INTERVAL', 300 ); // 5 dakika (varsayılan 60 saniye)

// WP-Cron Devre Dışı (Sistem Cron Kullanılacak)
define( 'DISABLE_WP_CRON', true );

// Concatenate Scripts (Admin panelinde script birleştirme)
define( 'CONCATENATE_SCRIPTS', true );

// Compress CSS
define( 'COMPRESS_CSS', true );

// Compress Scripts
define( 'COMPRESS_SCRIPTS', true );

// Enforce SSL (Eğer HTTPS kullanıyorsanız)
// define( 'FORCE_SSL_ADMIN', true );

// Redis Ayarları
define( 'WP_REDIS_DATABASE', 0 );
define( 'WP_REDIS_MAXTTL', 3600 );

/* Add any custom values between this line and the "stop editing" line. */

/* That's all, stop editing! Happy publishing. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
